// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace CompiledModels
{
    public partial class AppDbContextModel
    {
        partial void Initialize()
        {
            var author = AuthorEntityType.Create(this);
            var book = BookEntityType.Create(this);
            var publisher = PublisherEntityType.Create(this);
            var role = RoleEntityType.Create(this);
            var user = UserEntityType.Create(this);
            var userRole = UserRoleEntityType.Create(this);

            AuthorEntityType.CreateForeignKey1(author, user);
            BookEntityType.CreateForeignKey1(book, author);
            BookEntityType.CreateForeignKey2(book, publisher);
            UserRoleEntityType.CreateForeignKey1(userRole, role);
            UserRoleEntityType.CreateForeignKey2(userRole, user);

            AuthorEntityType.CreateAnnotations(author);
            BookEntityType.CreateAnnotations(book);
            PublisherEntityType.CreateAnnotations(publisher);
            RoleEntityType.CreateAnnotations(role);
            UserEntityType.CreateAnnotations(user);
            UserRoleEntityType.CreateAnnotations(userRole);

            AddAnnotation("ProductVersion", "6.0.9");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
